// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOI7qgm5qKu8ut_fXMiuMV6YVsHg_Dpw0',
    appId: '1:563535673587:web:ae6a92e782e3e993a51f86',
    messagingSenderId: '563535673587',
    projectId: 'changas-ya-cd978',
    authDomain: 'changas-ya-cd978.firebaseapp.com',
    storageBucket: 'changas-ya-cd978.firebasestorage.app',
    measurementId: 'G-P2LF4VX52N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvblEUjbrJRatYxEgVMWIFc9Oup0AyQGo',
    appId: '1:563535673587:android:e08e9789da505b66a51f86',
    messagingSenderId: '563535673587',
    projectId: 'changas-ya-cd978',
    storageBucket: 'changas-ya-cd978.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzbwy6HKmz1ARvIyS_sjXcfxjpK4YNf9I',
    appId: '1:563535673587:ios:4f286fd4426a70d3a51f86',
    messagingSenderId: '563535673587',
    projectId: 'changas-ya-cd978',
    storageBucket: 'changas-ya-cd978.firebasestorage.app',
    iosBundleId: 'com.example.changasYaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzbwy6HKmz1ARvIyS_sjXcfxjpK4YNf9I',
    appId: '1:563535673587:ios:4f286fd4426a70d3a51f86',
    messagingSenderId: '563535673587',
    projectId: 'changas-ya-cd978',
    storageBucket: 'changas-ya-cd978.firebasestorage.app',
    iosBundleId: 'com.example.changasYaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOI7qgm5qKu8ut_fXMiuMV6YVsHg_Dpw0',
    appId: '1:563535673587:web:834954a1de55227aa51f86',
    messagingSenderId: '563535673587',
    projectId: 'changas-ya-cd978',
    authDomain: 'changas-ya-cd978.firebaseapp.com',
    storageBucket: 'changas-ya-cd978.firebasestorage.app',
    measurementId: 'G-6VQG8R34FN',
  );
}
